### ISSUE TITLE
No attachments are added

### ISSUE THREAD

**Issue by tomkerswill** [sendgrid/sendgrid-perl#10]
Hi

I'm hitting a strange issue. After adding this line to the example code (and setting all the correct login credentials, etc.):

$sg->addAttachment('test.jpg');

... I find that the message sends correctly, but I do not see the attachment when I receive email. Is the attachment functionality definitely working correctly? Is there anything else required?

**Comment by eddiezane** [comment]
Fixed in the coming release. Thanks for reporting!
