### ISSUE TITLE
Unable to install module from CPAN

### ISSUE THREAD

**Issue by VictorAcatrinei** [sendgrid/sendgrid-perl#12]
When I try to run this command:
 sudo cpanm SendGrid-1.0.tar.gz

I get this error:

! Finding SendGrid-1.0.tar.gz on cpanmetadb failed.
! Finding SendGrid-1.0.tar.gz () on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution SendGrid-1.0.tar.gz

Could you guys have a look at this please? Thanks!

**Comment by brandonmwest** [comment]
This library is not available on cpan because of their ridiculous approval
process.

**Comment by ambrosechapel** [comment]
I believe that's not the correct answer to this problem.

The problem is that the instructions are missing a line:

    git clone https://github.com/sendgrid/sendgrid-perl.git
    sudo cpanm SendGrid-1.1.tar.gz

should be

    git clone https://github.com/sendgrid/sendgrid-perl.git
    cd sendgrid-perl
    sudo cpanm SendGrid-1.1.tar.gz

**Comment by brandonmwest** [comment]
We've since added it to CPAN :)

**Comment by ambrosechapel** [comment]
That doesn't mean the instructions are wrong. Despite this Issue being titled "Unable to install module from CPAN", VictorAcatrinei  is clearly trying to use the instructions on downloading via Git and installing via the cpanm command using the .tar.gz file.
