### ISSUE TITLE
cpanm installation instructions are missing the 'cd' command

### ISSUE THREAD

**Issue by ambrosechapel** [sendgrid/sendgrid-perl#14]
instructions are missing a line:

    git clone https://github.com/sendgrid/sendgrid-perl.git
    sudo cpanm SendGrid-1.1.tar.gz
should be

    git clone https://github.com/sendgrid/sendgrid-perl.git
    cd sendgrid-perl
    sudo cpanm SendGrid-1.1.tar.gz

**Comment by eddiezane** [comment]
Fixed - thanks!
